
import java.awt.Color;
import java.awt.event.ActionEvent;
import javax.swing.JButton;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author vv224843
 */
public class PaletteCouleur extends javax.swing.JFrame {

    /**
     * Creates new form PaletteCouleur
     */
    public PaletteCouleur() {
        initComponents();
        initPanneau();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Panneau = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        currentR = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        currentV = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        currentB = new javax.swing.JLabel();
        jButtonNew = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Panneau.setLayout(new java.awt.GridLayout(20, 20));
        getContentPane().add(Panneau, java.awt.BorderLayout.LINE_START);

        jPanel2.setLayout(new java.awt.GridLayout(10, 1));

        jLabel4.setText("Couleur");
        jPanel2.add(jLabel4);

        jLabel1.setText("Rouge");
        jPanel2.add(jLabel1);
        jPanel2.add(currentR);

        jLabel2.setText("Vert");
        jPanel2.add(jLabel2);
        jPanel2.add(currentV);

        jLabel3.setText("Bleu");
        jPanel2.add(jLabel3);
        jPanel2.add(currentB);

        jButtonNew.setText("Nouveau");
        jButtonNew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNewActionPerformed(evt);
            }
        });
        jPanel2.add(jButtonNew);

        getContentPane().add(jPanel2, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonNewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNewActionPerformed
        // TODO add your handling code here:
        currentR.setText("");
        currentV.setText("");
        currentB.setText("");
        for(int x=0;x<400;x++){
            JButton _bt = (JButton) Panneau.getComponent(x);
            int r = (int)(Math.random()*256);
            int v = (int)(Math.random()*256);
            int b = (int)(Math.random()*256);
            Color c = new Color(r,v,b);
            _bt.setBackground(c);
        }
    }//GEN-LAST:event_jButtonNewActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PaletteCouleur.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PaletteCouleur.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PaletteCouleur.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PaletteCouleur.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PaletteCouleur().setVisible(true);
            }
        });
    }
    
    public void initPanneau(){
        for(int x=0;x<400;x++){
            JButton bt = new JButton();
            bt.addActionListener(new java.awt.event.ActionListener() {
                @Override
                public void actionPerformed(ActionEvent e) {
                    btActionPerformed(e);
                }
            });
            int r = (int)(Math.random()*256);
            int v = (int)(Math.random()*256);
            int b = (int)(Math.random()*256);
            Color coul = new Color(r,v,b);
            bt.setBackground(coul);
            Panneau.add(bt);
        }
    }
    
    private void btActionPerformed(ActionEvent evt){
        JButton bt = (JButton)evt.getSource();
        Color c = bt.getBackground();
        
        for(int x=0;x<400;x++){
            JButton _bt = (JButton) Panneau.getComponent(x);
            _bt.setBackground(c);
        }
        
        currentR.setText(""+c.getRed());
        currentV.setText(""+c.getGreen());
        currentB.setText(""+c.getBlue());
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Panneau;
    private javax.swing.JLabel currentB;
    private javax.swing.JLabel currentR;
    private javax.swing.JLabel currentV;
    private javax.swing.JButton jButtonNew;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
