/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author vv224843
 */
public class Exo1 extends javax.swing.JFrame {

    /**
     * Creates new form Exo1
     */
    public Exo1() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        scultpeurimg = new javax.swing.JButton();
        marinimg = new javax.swing.JButton();
        patissierimg = new javax.swing.JButton();
        informaticienimg = new javax.swing.JButton();
        peintreimg = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jImg = new javax.swing.JButton();
        jText = new javax.swing.JButton();
        jResultat = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        peintretext = new javax.swing.JButton();
        patisseurtext = new javax.swing.JButton();
        informaticientext = new javax.swing.JButton();
        sculpteurtext = new javax.swing.JButton();
        marintext = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Le jeu des métiers");
        getContentPane().add(jLabel1, java.awt.BorderLayout.NORTH);

        jPanel1.setLayout(new java.awt.GridLayout(5, 1));

        scultpeurimg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Sculpteur.gif"))); // NOI18N
        scultpeurimg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                scultpeurimgActionPerformed(evt);
            }
        });
        jPanel1.add(scultpeurimg);

        marinimg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Marin.gif"))); // NOI18N
        marinimg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                marinimgActionPerformed(evt);
            }
        });
        jPanel1.add(marinimg);

        patissierimg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Patissier.gif"))); // NOI18N
        patissierimg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                patissierimgActionPerformed(evt);
            }
        });
        jPanel1.add(patissierimg);

        informaticienimg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Informaticien.gif"))); // NOI18N
        informaticienimg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                informaticienimgActionPerformed(evt);
            }
        });
        jPanel1.add(informaticienimg);

        peintreimg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Peintre.gif"))); // NOI18N
        peintreimg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                peintreimgActionPerformed(evt);
            }
        });
        jPanel1.add(peintreimg);

        getContentPane().add(jPanel1, java.awt.BorderLayout.WEST);

        jPanel2.setLayout(new java.awt.GridLayout(3, 1));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 126, Short.MAX_VALUE)
        );

        jPanel2.add(jPanel3);

        jPanel4.setLayout(new java.awt.GridLayout(1, 2));

        jImg.setText("Image");
        jPanel4.add(jImg);

        jText.setText("Métier");
        jPanel4.add(jText);

        jPanel2.add(jPanel4);

        jResultat.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jResultat.setText("Résultat");
        jPanel2.add(jResultat);

        getContentPane().add(jPanel2, java.awt.BorderLayout.CENTER);

        jPanel5.setLayout(new java.awt.GridLayout(5, 1));

        peintretext.setText("Peintre");
        peintretext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                peintretextActionPerformed(evt);
            }
        });
        jPanel5.add(peintretext);

        patisseurtext.setText("Patissier");
        patisseurtext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                patisseurtextActionPerformed(evt);
            }
        });
        jPanel5.add(patisseurtext);

        informaticientext.setText("Informaticien");
        informaticientext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                informaticientextActionPerformed(evt);
            }
        });
        jPanel5.add(informaticientext);

        sculpteurtext.setText("Sculpteur");
        sculpteurtext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sculpteurtextActionPerformed(evt);
            }
        });
        jPanel5.add(sculpteurtext);

        marintext.setText("Marin");
        marintext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                marintextActionPerformed(evt);
            }
        });
        jPanel5.add(marintext);

        getContentPane().add(jPanel5, java.awt.BorderLayout.EAST);

        jMenu1.setText("jeu");

        jMenuItem1.setText("rejouer");
        jMenu1.add(jMenuItem1);

        jMenuItem2.setText("quitter");
        jMenu1.add(jMenuItem2);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void peintretextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_peintretextActionPerformed
        jText.setText("Peintre");
        result();
    }//GEN-LAST:event_peintretextActionPerformed

    private void scultpeurimgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_scultpeurimgActionPerformed
        jImg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Sculpteur.gif"))); // NOI18N
        jImg.setText("");
        jImg.setName("Sculpteur");
        result();
    }//GEN-LAST:event_scultpeurimgActionPerformed

    private void marinimgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_marinimgActionPerformed
        jImg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Marin.gif"))); // NOI18N
        jImg.setText("");
        jImg.setName("Marin");
        result();
    }//GEN-LAST:event_marinimgActionPerformed

    private void patissierimgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_patissierimgActionPerformed
        jImg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Patissier.gif")));
        jImg.setText("");
        jImg.setName("Patissier");
        result();
    }//GEN-LAST:event_patissierimgActionPerformed

    private void informaticienimgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_informaticienimgActionPerformed
        jImg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Informaticien.gif"))); // NOI18N
        jImg.setText("");
        jImg.setName("Informaticien");
        result();
    }//GEN-LAST:event_informaticienimgActionPerformed

    private void patisseurtextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_patisseurtextActionPerformed
        jText.setText("Patissier");
        result();
    }//GEN-LAST:event_patisseurtextActionPerformed

    private void informaticientextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_informaticientextActionPerformed
        jText.setText("Informaticien");
        result();
    }//GEN-LAST:event_informaticientextActionPerformed

    private void sculpteurtextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sculpteurtextActionPerformed
        jText.setText("Sculpteur");
        result();
    }//GEN-LAST:event_sculpteurtextActionPerformed

    private void marintextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_marintextActionPerformed
        jText.setText("Marin");
        result();
    }//GEN-LAST:event_marintextActionPerformed

    private void peintreimgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_peintreimgActionPerformed
        jImg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Peintre.gif"))); // NOI18N
        jImg.setText("");
        jImg.setName("Peintre");
        result();
    }//GEN-LAST:event_peintreimgActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Exo1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Exo1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Exo1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Exo1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Exo1().setVisible(true);
            }
        });
    }
    
    private void result(){
        if(!(jText.getText().equals("Image")||jText.getText().equals("Métier"))){
            if(gagne()){
                jResultat.setText("Gagné!");
            }else{
                jResultat.setText("Perdu !");
            }   
        }
    }
    
    private boolean gagne(){
        return jImg.getName().equals(jText.getText());
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton informaticienimg;
    private javax.swing.JButton informaticientext;
    private javax.swing.JButton jImg;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JLabel jResultat;
    private javax.swing.JButton jText;
    private javax.swing.JButton marinimg;
    private javax.swing.JButton marintext;
    private javax.swing.JButton patisseurtext;
    private javax.swing.JButton patissierimg;
    private javax.swing.JButton peintreimg;
    private javax.swing.JButton peintretext;
    private javax.swing.JButton sculpteurtext;
    private javax.swing.JButton scultpeurimg;
    // End of variables declaration//GEN-END:variables
}
