
import java.awt.Color;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author vv224843
 */
public class Exo2 extends javax.swing.JFrame {
    
    private Color couleur1;
    private Color couleur2;
    private int num;
    private boolean deuxCouleur = false;

    /**
     * Creates new form Exo1
     */
    public Exo2() {
        initComponents();
        num=1;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jlabel0 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        bleu = new javax.swing.JButton();
        vert = new javax.swing.JButton();
        rouge = new javax.swing.JButton();
        orange = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        centre = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        marron = new javax.swing.JButton();
        jaune = new javax.swing.JButton();
        rose = new javax.swing.JButton();
        violet = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jlabel0.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlabel0.setText("Mélangez les deux couleurs en cliquant sur les deux boutons!");
        getContentPane().add(jlabel0, java.awt.BorderLayout.SOUTH);

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Le jeu des couleurs");
        getContentPane().add(jLabel1, java.awt.BorderLayout.NORTH);

        jPanel1.setLayout(new java.awt.GridLayout(4, 1));

        bleu.setBackground(new java.awt.Color(0, 0, 255));
        bleu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bleuActionPerformed(evt);
            }
        });
        jPanel1.add(bleu);

        vert.setBackground(new java.awt.Color(0, 255, 0));
        vert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vertActionPerformed(evt);
            }
        });
        jPanel1.add(vert);

        rouge.setBackground(new java.awt.Color(255, 0, 0));
        rouge.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rougeActionPerformed(evt);
            }
        });
        jPanel1.add(rouge);

        orange.setBackground(new java.awt.Color(255, 153, 51));
        orange.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                orangeActionPerformed(evt);
            }
        });
        jPanel1.add(orange);

        getContentPane().add(jPanel1, java.awt.BorderLayout.WEST);

        jPanel2.setLayout(new java.awt.GridLayout(1, 1));
        jPanel2.add(centre);

        getContentPane().add(jPanel2, java.awt.BorderLayout.CENTER);

        jPanel5.setLayout(new java.awt.GridLayout(4, 1));

        marron.setBackground(new java.awt.Color(153, 102, 0));
        marron.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                marronActionPerformed(evt);
            }
        });
        jPanel5.add(marron);

        jaune.setBackground(new java.awt.Color(255, 255, 51));
        jaune.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jauneActionPerformed(evt);
            }
        });
        jPanel5.add(jaune);

        rose.setBackground(new java.awt.Color(255, 102, 255));
        rose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                roseActionPerformed(evt);
            }
        });
        jPanel5.add(rose);

        violet.setBackground(new java.awt.Color(102, 0, 102));
        violet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                violetActionPerformed(evt);
            }
        });
        jPanel5.add(violet);

        getContentPane().add(jPanel5, java.awt.BorderLayout.EAST);

        jMenu1.setText("jeu");

        jMenuItem1.setText("rejouer");
        jMenu1.add(jMenuItem1);

        jMenuItem2.setText("quitter");
        jMenu1.add(jMenuItem2);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void marronActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_marronActionPerformed
        roulementCouleur(marron.getBackground());
    }//GEN-LAST:event_marronActionPerformed

    private void bleuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bleuActionPerformed
        roulementCouleur(bleu.getBackground());
    }//GEN-LAST:event_bleuActionPerformed

    private void vertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vertActionPerformed
        roulementCouleur(vert.getBackground());
    }//GEN-LAST:event_vertActionPerformed

    private void rougeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rougeActionPerformed
        roulementCouleur(rouge.getBackground());
    }//GEN-LAST:event_rougeActionPerformed

    private void orangeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_orangeActionPerformed
        roulementCouleur(orange.getBackground());        
    }//GEN-LAST:event_orangeActionPerformed

    private void jauneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jauneActionPerformed
        roulementCouleur(jaune.getBackground());                
    }//GEN-LAST:event_jauneActionPerformed

    private void roseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_roseActionPerformed
        roulementCouleur(rose.getBackground());                
    }//GEN-LAST:event_roseActionPerformed

    private void violetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_violetActionPerformed
        roulementCouleur(violet.getBackground());                
    }//GEN-LAST:event_violetActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Exo1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Exo1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Exo1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Exo1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Exo2().setVisible(true);
            }
        });
    }
    
    
    private void roulementCouleur(Color receive1){
        if(num==1){
            couleur1=receive1;
            num=2;
        }else{
            couleur2=receive1;
            num=1;
            deuxCouleur=true;
        }
        melanger();
    }
    
    private void melanger(){
        if(deuxCouleur){
            int R = (couleur1.getRed()+couleur2.getRed())/2;
            int G = (couleur1.getGreen()+couleur2.getGreen())/2;
            int B = (couleur1.getBlue()+couleur2.getBlue())/2;
            centre.setBackground(new Color(R,G,B));
        }
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bleu;
    private javax.swing.JButton centre;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JButton jaune;
    private javax.swing.JLabel jlabel0;
    private javax.swing.JButton marron;
    private javax.swing.JButton orange;
    private javax.swing.JButton rose;
    private javax.swing.JButton rouge;
    private javax.swing.JButton vert;
    private javax.swing.JButton violet;
    // End of variables declaration//GEN-END:variables
}
