
import java.awt.Color;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author vv224843
 */
public class Exo4 extends javax.swing.JFrame {

    /**
     * Creates new form Exo4
     */
    public Exo4() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroupRadio = new javax.swing.ButtonGroup();
        buttonGroupCheckBox = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jPanelCouleurDeFond = new javax.swing.JPanel();
        jLabelCouleurDeFond = new javax.swing.JLabel();
        jPanelCDFRadio = new javax.swing.JPanel();
        jRadioButtonRouge = new javax.swing.JRadioButton();
        jRadioButtonVert = new javax.swing.JRadioButton();
        jRadioButtonBleu = new javax.swing.JRadioButton();
        jRadioButtonOrange = new javax.swing.JRadioButton();
        jPanelCDFRadioDesc = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jPanelFonte = new javax.swing.JPanel();
        jLabelFonte = new javax.swing.JLabel();
        jPanelFonteCheckBox = new javax.swing.JPanel();
        jCheckBox1 = new javax.swing.JCheckBox();
        jCheckBox2 = new javax.swing.JCheckBox();
        jCheckBox3 = new javax.swing.JCheckBox();
        jCheckBox4 = new javax.swing.JCheckBox();
        jPanelFonteCheckBoxDesc = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jPanelCouleurDEcriture = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jToggleButtonRose = new javax.swing.JToggleButton();
        jToggleButtonMagenta = new javax.swing.JToggleButton();
        jToggleButtonJaune = new javax.swing.JToggleButton();
        jToggleButtonGris = new javax.swing.JToggleButton();
        preview = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Choisissez les paramètres de votre boutton !");
        getContentPane().add(jLabel1, java.awt.BorderLayout.NORTH);

        jPanel1.setLayout(new java.awt.GridLayout(2, 2));

        jPanelCouleurDeFond.setLayout(new java.awt.BorderLayout());

        jLabelCouleurDeFond.setText("Couleur de fond ?");
        jPanelCouleurDeFond.add(jLabelCouleurDeFond, java.awt.BorderLayout.NORTH);

        jPanelCDFRadio.setLayout(new java.awt.GridLayout(4, 0));

        buttonGroupRadio.add(jRadioButtonRouge);
        jRadioButtonRouge.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonRougeActionPerformed(evt);
            }
        });
        jPanelCDFRadio.add(jRadioButtonRouge);

        buttonGroupRadio.add(jRadioButtonVert);
        jRadioButtonVert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonVertActionPerformed(evt);
            }
        });
        jPanelCDFRadio.add(jRadioButtonVert);

        buttonGroupRadio.add(jRadioButtonBleu);
        jRadioButtonBleu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonBleuActionPerformed(evt);
            }
        });
        jPanelCDFRadio.add(jRadioButtonBleu);

        buttonGroupRadio.add(jRadioButtonOrange);
        jRadioButtonOrange.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonOrangeActionPerformed(evt);
            }
        });
        jPanelCDFRadio.add(jRadioButtonOrange);

        jPanelCouleurDeFond.add(jPanelCDFRadio, java.awt.BorderLayout.WEST);

        jPanelCDFRadioDesc.setLayout(new java.awt.GridLayout(4, 0));

        jLabel3.setText("Rouge");
        jPanelCDFRadioDesc.add(jLabel3);

        jLabel4.setText("Vert");
        jPanelCDFRadioDesc.add(jLabel4);

        jLabel5.setText("Bleu");
        jPanelCDFRadioDesc.add(jLabel5);

        jLabel6.setText("Orange");
        jPanelCDFRadioDesc.add(jLabel6);

        jPanelCouleurDeFond.add(jPanelCDFRadioDesc, java.awt.BorderLayout.CENTER);

        jPanel1.add(jPanelCouleurDeFond);

        jPanelFonte.setLayout(new java.awt.BorderLayout());

        jLabelFonte.setText("Fonte d'écrire ?");
        jPanelFonte.add(jLabelFonte, java.awt.BorderLayout.NORTH);

        jPanelFonteCheckBox.setLayout(new java.awt.GridLayout(4, 0));

        buttonGroupCheckBox.add(jCheckBox1);
        jCheckBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox1ActionPerformed(evt);
            }
        });
        jPanelFonteCheckBox.add(jCheckBox1);

        buttonGroupCheckBox.add(jCheckBox2);
        jCheckBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox2ActionPerformed(evt);
            }
        });
        jPanelFonteCheckBox.add(jCheckBox2);

        buttonGroupCheckBox.add(jCheckBox3);
        jCheckBox3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox3ActionPerformed(evt);
            }
        });
        jPanelFonteCheckBox.add(jCheckBox3);

        buttonGroupCheckBox.add(jCheckBox4);
        jCheckBox4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox4ActionPerformed(evt);
            }
        });
        jPanelFonteCheckBox.add(jCheckBox4);

        jPanelFonte.add(jPanelFonteCheckBox, java.awt.BorderLayout.WEST);

        jPanelFonteCheckBoxDesc.setLayout(new java.awt.GridLayout(4, 0));

        jLabel8.setText("Tahoma 36");
        jPanelFonteCheckBoxDesc.add(jLabel8);

        jLabel9.setText("Tahoma 48");
        jPanelFonteCheckBoxDesc.add(jLabel9);

        jLabel10.setText("Lucida Calligarphy 36");
        jPanelFonteCheckBoxDesc.add(jLabel10);

        jLabel11.setText("Arial 18");
        jPanelFonteCheckBoxDesc.add(jLabel11);

        jPanelFonte.add(jPanelFonteCheckBoxDesc, java.awt.BorderLayout.CENTER);

        jPanel1.add(jPanelFonte);

        jPanelCouleurDEcriture.setLayout(new java.awt.GridLayout(5, 0));

        jLabel2.setText("Couleur d'écriture ?");
        jPanelCouleurDEcriture.add(jLabel2);

        jToggleButtonRose.setText("Rose");
        jToggleButtonRose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButtonRoseActionPerformed(evt);
            }
        });
        jPanelCouleurDEcriture.add(jToggleButtonRose);

        jToggleButtonMagenta.setText("Magenta");
        jToggleButtonMagenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButtonMagentaActionPerformed(evt);
            }
        });
        jPanelCouleurDEcriture.add(jToggleButtonMagenta);

        jToggleButtonJaune.setText("Jaune");
        jToggleButtonJaune.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButtonJauneActionPerformed(evt);
            }
        });
        jPanelCouleurDEcriture.add(jToggleButtonJaune);

        jToggleButtonGris.setText("Gris");
        jToggleButtonGris.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButtonGrisActionPerformed(evt);
            }
        });
        jPanelCouleurDEcriture.add(jToggleButtonGris);

        jPanel1.add(jPanelCouleurDEcriture);

        preview.setText("TEXTE");
        jPanel1.add(preview);

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jToggleButtonMagentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButtonMagentaActionPerformed
        preview.setForeground(Color.magenta);
    }//GEN-LAST:event_jToggleButtonMagentaActionPerformed

    private void jToggleButtonGrisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButtonGrisActionPerformed
        preview.setForeground(Color.gray);
    }//GEN-LAST:event_jToggleButtonGrisActionPerformed

    private void jCheckBox4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox4ActionPerformed
        changeFont(new java.awt.Font("Arial", 0,18));
    }//GEN-LAST:event_jCheckBox4ActionPerformed

    private void jCheckBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox1ActionPerformed
        changeFont(new java.awt.Font("Tahoma", 0,36));
    }//GEN-LAST:event_jCheckBox1ActionPerformed

    private void jCheckBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox2ActionPerformed
        changeFont(new java.awt.Font("Tahoma", 0,48));
    }//GEN-LAST:event_jCheckBox2ActionPerformed

    private void jCheckBox3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox3ActionPerformed
        changeFont(new java.awt.Font("Lucida Calligray 36", 0,48));
    }//GEN-LAST:event_jCheckBox3ActionPerformed

    private void jRadioButtonRougeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonRougeActionPerformed
        preview.setBackground(Color.red);
    }//GEN-LAST:event_jRadioButtonRougeActionPerformed

    private void jRadioButtonVertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonVertActionPerformed
        preview.setBackground(Color.green);
    }//GEN-LAST:event_jRadioButtonVertActionPerformed

    private void jRadioButtonBleuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonBleuActionPerformed
        preview.setBackground(Color.blue);
    }//GEN-LAST:event_jRadioButtonBleuActionPerformed

    private void jRadioButtonOrangeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonOrangeActionPerformed
        preview.setBackground(Color.orange);
    }//GEN-LAST:event_jRadioButtonOrangeActionPerformed

    private void jToggleButtonRoseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButtonRoseActionPerformed
        preview.setForeground(Color.pink);
    }//GEN-LAST:event_jToggleButtonRoseActionPerformed

    private void jToggleButtonJauneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButtonJauneActionPerformed
        preview.setForeground(Color.yellow);
    }//GEN-LAST:event_jToggleButtonJauneActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Exo4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Exo4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Exo4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Exo4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Exo4().setVisible(true);
            }
        });
    }
    
    public void changeFont(java.awt.Font toChange){
        preview.setFont(toChange);
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.ButtonGroup buttonGroupCheckBox;
    private javax.swing.ButtonGroup buttonGroupRadio;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JCheckBox jCheckBox2;
    private javax.swing.JCheckBox jCheckBox3;
    private javax.swing.JCheckBox jCheckBox4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelCouleurDeFond;
    private javax.swing.JLabel jLabelFonte;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanelCDFRadio;
    private javax.swing.JPanel jPanelCDFRadioDesc;
    private javax.swing.JPanel jPanelCouleurDEcriture;
    private javax.swing.JPanel jPanelCouleurDeFond;
    private javax.swing.JPanel jPanelFonte;
    private javax.swing.JPanel jPanelFonteCheckBox;
    private javax.swing.JPanel jPanelFonteCheckBoxDesc;
    private javax.swing.JRadioButton jRadioButtonBleu;
    private javax.swing.JRadioButton jRadioButtonOrange;
    private javax.swing.JRadioButton jRadioButtonRouge;
    private javax.swing.JRadioButton jRadioButtonVert;
    private javax.swing.JToggleButton jToggleButtonGris;
    private javax.swing.JToggleButton jToggleButtonJaune;
    private javax.swing.JToggleButton jToggleButtonMagenta;
    private javax.swing.JToggleButton jToggleButtonRose;
    private javax.swing.JButton preview;
    // End of variables declaration//GEN-END:variables
}
