/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package jeumemory.ui;

import java.awt.Image;
import java.awt.Toolkit;
import java.util.ArrayList;
import javax.swing.DefaultListModel;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import jeumemory.Joueur;
import jeumemory.LesFamilles;
import jeumemory.LesPersonnages;

/**
 *
 * @author Valentin
 */
public class SaisieJoueurDlg extends javax.swing.JDialog {
    
    private static final String TAG = SaisieJoueurDlg.class.getName();
    
    private setOnNewPlayerCreated listener;
    private LesPersonnages charactersList;
    private Joueur newPlayer;
    private ImageIcon playerIcon;
    
    public interface setOnNewPlayerCreated{
        void onNewPlayerCreated(Joueur newPlayer);
    }
    
    /**
     * Creates new form SaisieJoueurDlg
     */
    public SaisieJoueurDlg(java.awt.Frame parent, boolean modal, LesPersonnages charactersList,setOnNewPlayerCreated listener) {
        super(parent, modal);
        this.charactersList = charactersList;
        this.listener = listener;
        initComponents();
        initFamilyList();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        userInput = new javax.swing.JTextArea();
        jPanel6 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        FamilyList = new javax.swing.JList<>();
        jPanel5 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        Parcourir = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        Photo = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        Cancel = new javax.swing.JButton();
        Submit = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Créez votre joueur !");
        getContentPane().add(jLabel1, java.awt.BorderLayout.PAGE_START);

        jPanel1.setLayout(new java.awt.GridLayout(1, 2));

        jPanel4.setLayout(new java.awt.GridLayout(3, 0));

        jPanel7.setLayout(new java.awt.BorderLayout());

        jLabel2.setText("Donnez votre pseudo");
        jPanel7.add(jLabel2, java.awt.BorderLayout.NORTH);

        userInput.setColumns(20);
        userInput.setRows(5);
        jScrollPane1.setViewportView(userInput);

        jPanel7.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        jPanel4.add(jPanel7);

        jPanel6.setLayout(new java.awt.BorderLayout());

        jLabel3.setText("Quelle est votre famille préférée de personnages ?");
        jPanel6.add(jLabel3, java.awt.BorderLayout.PAGE_START);

        FamilyList.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane2.setViewportView(FamilyList);

        jPanel6.add(jScrollPane2, java.awt.BorderLayout.CENTER);

        jPanel4.add(jPanel6);

        jPanel5.setLayout(new java.awt.BorderLayout());

        jLabel4.setText("Choississez une photo");
        jPanel5.add(jLabel4, java.awt.BorderLayout.NORTH);

        Parcourir.setText("Parcourir");
        Parcourir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ParcourirActionPerformed(evt);
            }
        });
        jPanel5.add(Parcourir, java.awt.BorderLayout.CENTER);

        jPanel4.add(jPanel5);

        jPanel1.add(jPanel4);

        jPanel2.setLayout(new java.awt.BorderLayout());

        Photo.setBorder(null);
        jPanel2.add(Photo, java.awt.BorderLayout.CENTER);

        jPanel3.setLayout(new java.awt.GridLayout(1, 2));

        Cancel.setText("Annuler");
        Cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelActionPerformed(evt);
            }
        });
        jPanel3.add(Cancel);

        Submit.setText("Valider");
        Submit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SubmitActionPerformed(evt);
            }
        });
        jPanel3.add(Submit);

        jPanel2.add(jPanel3, java.awt.BorderLayout.SOUTH);

        jPanel1.add(jPanel2);

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void initFamilyList(){
        if(charactersList!=null){
            DefaultListModel mod = new DefaultListModel();
            ArrayList<String> allFamilyName = charactersList.getStringToutesLesFamilles();
            for(int x=0;x<allFamilyName.size();x++){
                mod.addElement(allFamilyName.get(x));
            }
            FamilyList.setModel(mod);
        }else{
            System.out.println(TAG+" charactersList is null");
        }
    }
    private void CancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelActionPerformed
        this.setVisible(false);
        this.dispose();
    }//GEN-LAST:event_CancelActionPerformed

    private void ParcourirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ParcourirActionPerformed
        JFileChooser jf= new JFileChooser();
        if (jf.showOpenDialog(this)== JFileChooser.APPROVE_OPTION){ 
            String path = jf.getSelectedFile().getPath(); 
            Image img=Toolkit.getDefaultToolkit().getImage(path);
            img=img.getScaledInstance(Photo.getWidth()-10, Photo.getHeight()-10, Image.SCALE_DEFAULT);
            ImageIcon photo = new ImageIcon(img);
            playerIcon = photo ;
            Photo.setIcon(photo);
        }
    }//GEN-LAST:event_ParcourirActionPerformed

    private void SubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SubmitActionPerformed
        String Error1 = "Vous devez entrer votre pseudo ici";
        String Error2 = "Vous devez choisisr une famille préféré";
        String pseudo = userInput.getText();
        if(pseudo!=null&&pseudo.length()>0&&!pseudo.equals(Error2)&&!pseudo.equals(Error1)){ // On vérifie que l'utilisateur a bien rentrer une valeur correcte
            int selectedFamily = FamilyList.getSelectedIndex();
            if(selectedFamily!=-1){ // on vérifie que l'utlisateur a bien choisit une famille
                String favoriteFamily = (String) FamilyList.getModel().getElementAt(selectedFamily);
                if(playerIcon!=null){ // on vérifie que l'utilisateur a bien choisit une image. Si c'est le cas, on crée le joueur avec la photo choisit
                    newPlayer = new Joueur(pseudo,playerIcon,LesFamilles.getFamilleByName(favoriteFamily));
                }else{ // Si le joueur n'a pas sélectionner de photo, on lui met une photo anonyme
                    ImageIcon anonym = new ImageIcon(getClass().getResource("/jeumemory/img/joueurDefaut.jpg"));
                    newPlayer = new Joueur(pseudo,anonym,LesFamilles.getFamilleByName(favoriteFamily));
                }
                listener.onNewPlayerCreated(newPlayer); // on retourne le joueur crée
                this.setVisible(false);
                this.dispose();
            }else{ 
                userInput.setText(Error2);
            }
        }else{
            userInput.setText(Error1);
        }
    }//GEN-LAST:event_SubmitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SaisieJoueurDlg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SaisieJoueurDlg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SaisieJoueurDlg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SaisieJoueurDlg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                SaisieJoueurDlg dialog = new SaisieJoueurDlg(new javax.swing.JFrame(), true, null, null);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Cancel;
    private javax.swing.JList<String> FamilyList;
    private javax.swing.JButton Parcourir;
    private javax.swing.JButton Photo;
    private javax.swing.JButton Submit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea userInput;
    // End of variables declaration//GEN-END:variables
}
