package jeumemory;

import java.awt.Image;
import javax.swing.ImageIcon;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author vv224843
 */
public class InitDialog extends javax.swing.JDialog {
    
    Image LaraImg;
    Joueur Lara = new Joueur("Lara",LaraImg);
    
    Image JackImg = new ImageIcon(getClass().getResource("/jeumemory/img/anonyme.png")).getImage();
    Joueur Jack = new Joueur("Jack",JackImg);
    
    Image JSImg;
    Joueur JS = new Joueur("Jean-Sébastien",JSImg);
    
    Image AmadeusImg;
    Joueur Amadeus = new Joueur("Amadeus",AmadeusImg);
    
    /**
     * Creates new form InitDialog
     */
    public InitDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel6 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        Bphoto = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        Cancel = new javax.swing.JButton();
        Submit = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jRadioButtonChild = new javax.swing.JRadioButton();
        jRadioButtonBeginner = new javax.swing.JRadioButton();
        jRadioButtonAdvance = new javax.swing.JRadioButton();
        jRadioButtonExpert = new javax.swing.JRadioButton();
        jPanel8 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel10 = new javax.swing.JPanel();
        jCheckBoxLara = new javax.swing.JCheckBox();
        jCheckBoxJack = new javax.swing.JCheckBox();
        jCheckBoxJS = new javax.swing.JCheckBox();
        jCheckBoxAmadeus = new javax.swing.JCheckBox();
        jPanel11 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel6.setLayout(new java.awt.GridLayout(2, 0));

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jPanel6.add(jScrollPane1);
        jPanel6.add(Bphoto);

        getContentPane().add(jPanel6, java.awt.BorderLayout.EAST);

        jPanel1.setLayout(new java.awt.GridLayout(1, 2));

        Cancel.setText("Annuler");
        Cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelActionPerformed(evt);
            }
        });
        jPanel1.add(Cancel);

        Submit.setText("Valider");
        Submit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SubmitActionPerformed(evt);
            }
        });
        jPanel1.add(Submit);

        getContentPane().add(jPanel1, java.awt.BorderLayout.SOUTH);

        jPanel2.setLayout(new java.awt.GridLayout(1, 2));

        jPanel7.setLayout(new java.awt.BorderLayout());

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Choissisez la taille du jeu");
        jPanel7.add(jLabel1, java.awt.BorderLayout.NORTH);

        jPanel4.setLayout(new java.awt.GridLayout(4, 1));
        jPanel4.add(jRadioButtonChild);
        jPanel4.add(jRadioButtonBeginner);
        jPanel4.add(jRadioButtonAdvance);
        jPanel4.add(jRadioButtonExpert);

        jPanel7.add(jPanel4, java.awt.BorderLayout.WEST);

        jPanel8.setLayout(new java.awt.GridLayout(4, 1));

        jLabel6.setText("Enfant ( 8 cartes )");
        jPanel8.add(jLabel6);

        jLabel7.setText("Débutant ( 20 cartes )");
        jPanel8.add(jLabel7);

        jLabel8.setText("Avancé ( 36 cartes )");
        jPanel8.add(jLabel8);

        jLabel9.setText("Expert ( 64 cartes )");
        jPanel8.add(jLabel9);

        jPanel7.add(jPanel8, java.awt.BorderLayout.CENTER);

        jPanel2.add(jPanel7);

        jPanel9.setLayout(new java.awt.BorderLayout());

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Choisissez les joueurs créés par défaut");
        jPanel9.add(jLabel2, java.awt.BorderLayout.NORTH);

        jPanel10.setLayout(new java.awt.GridLayout(4, 1));

        jCheckBoxLara.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxLaraActionPerformed(evt);
            }
        });
        jPanel10.add(jCheckBoxLara);

        jCheckBoxJack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxJackActionPerformed(evt);
            }
        });
        jPanel10.add(jCheckBoxJack);

        jCheckBoxJS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxJSActionPerformed(evt);
            }
        });
        jPanel10.add(jCheckBoxJS);

        jCheckBoxAmadeus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxAmadeusActionPerformed(evt);
            }
        });
        jPanel10.add(jCheckBoxAmadeus);

        jPanel9.add(jPanel10, java.awt.BorderLayout.WEST);

        jPanel11.setLayout(new java.awt.GridLayout(4, 1));

        jLabel10.setText("Lara");
        jPanel11.add(jLabel10);

        jLabel11.setText("Jack");
        jPanel11.add(jLabel11);

        jLabel12.setText("Jean-Sébastien");
        jPanel11.add(jLabel12);

        jLabel13.setText("Amadeus");
        jPanel11.add(jLabel13);

        jPanel9.add(jPanel11, java.awt.BorderLayout.CENTER);

        jPanel2.add(jPanel9);

        getContentPane().add(jPanel2, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jCheckBoxLaraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxLaraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBoxLaraActionPerformed

    private void jCheckBoxJackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxJackActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBoxJackActionPerformed

    private void jCheckBoxJSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxJSActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBoxJSActionPerformed

    private void jCheckBoxAmadeusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxAmadeusActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBoxAmadeusActionPerformed

    private void CancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CancelActionPerformed

    private void SubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SubmitActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SubmitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InitDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InitDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InitDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InitDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                InitDialog dialog = new InitDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Bphoto;
    private javax.swing.JButton Cancel;
    private javax.swing.JButton Submit;
    private javax.swing.JCheckBox jCheckBoxAmadeus;
    private javax.swing.JCheckBox jCheckBoxJS;
    private javax.swing.JCheckBox jCheckBoxJack;
    private javax.swing.JCheckBox jCheckBoxLara;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JRadioButton jRadioButtonAdvance;
    private javax.swing.JRadioButton jRadioButtonBeginner;
    private javax.swing.JRadioButton jRadioButtonChild;
    private javax.swing.JRadioButton jRadioButtonExpert;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
}
